### ISSUE TITLE
capacitor 6

### ISSUE THREAD

**Issue by tbo47** [Andrea055/capacitor-plugin-wifi#2]
Thanks for the plugin, it works great.

I needed the plugin to work with Capacitor 6. It pushed it here https://github.com/tbo47/capacitor-plugin-wifi-6

Let me know if you want me to contribute back to your project.

**Comment by andreock** [comment]
Sure, contribution is welcome. Open a pull request, I'll review it

Inviato da Proton Mail Android

-------- Messaggio originale --------
13/12/24 14:56, Teebo  ha scritto:
